[DEFAULT]

; Logging level: ERROR, WARNING, INFO, DEBUG
LOGGING = INFO

; How often to recalculate DC system power (seconds)
UPDATE_INTERVAL = 1

; How often to emit a summary log line (seconds)
LOG_INTERVAL = 300

; Keyword to identify SmartShunt devices by ProductName
SMARTSHUNT_KEYWORD = SmartShunt
